### ISSUE TITLE
Try to install EVA-pipeline 

### ISSUE THREAD

**Issue by silenus092** [EBIvariation/eva-pipeline#125]
I follow installation instructions; 
`git clone https://github.com/EBIvariation/opencga.git`
`cd opencga && mvn clean install -DskipTests`

error said 

[INFO] 11 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] opencga ........................................... SUCCESS [0.149s]
[INFO] opencga-lib ....................................... SUCCESS [3.248s]
[INFO] opencga-storage ................................... SUCCESS [0.004s]
[INFO] opencga-storage-core .............................. FAILURE [1.250s]
[INFO] opencga-catalog ................................... SKIPPED
[INFO] opencga-analysis .................................. SKIPPED
[INFO] opencga-storage-mongodb ........................... SKIPPED
[INFO] opencga-storage-app ............................... SKIPPED
[INFO] opencga-app ....................................... SKIPPED
[INFO] opencga-account ................................... SKIPPED
[INFO] opencga-storage-hbase ............................. SKIPPED
[INFO] opencga-server .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.332s
[INFO] Finished at: Fri Aug 11 07:46:39 UTC 2017
[INFO] Final Memory: 23M/252M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project opencga-storage-core: Compilation failure: Compilation failure:
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/VepVariantAnnotator.java:[7,39] package org.opencb.cellbase.core.client does not exist
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[12,32] cannot find symbol
[ERROR] symbol:   class CellBaseConfiguration
[ERROR] location: package org.opencb.cellbase.core
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[13,39] package org.opencb.cellbase.core.client does not exist
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[14,44] cannot find symbol
[ERROR] symbol:   class CellbaseConfiguration
[ERROR] location: package org.opencb.cellbase.core.common.core
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[44,13] cannot find symbol
[ERROR] symbol:   class CellBaseClient
[ERROR] location: class org.opencb.opencga.storage.core.variant.annotation.CellBaseVariantAnnotator
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[82,37] cannot find symbol
[ERROR] symbol:   class CellBaseClient
[ERROR] location: class org.opencb.opencga.storage.core.variant.annotation.CellBaseVariantAnnotator
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[100,13] cannot find symbol
[ERROR] symbol:   class CellBaseClient
[ERROR] location: class org.opencb.opencga.storage.core.variant.annotation.CellBaseVariantAnnotator
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[103,38] cannot find symbol
[ERROR] symbol:   class CellBaseClient
[ERROR] location: class org.opencb.opencga.storage.core.variant.annotation.CellBaseVariantAnnotator
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[243,35] package CellBaseClient does not exist
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[244,35] package CellBaseClient does not exist
[ERROR] /mnt/speedSeq_data/opencga/opencga-storage/opencga-storage-core/src/main/java/org/opencb/opencga/storage/core/variant/annotation/CellBaseVariantAnnotator.java:[246,35] package CellBaseClient does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :opencga-storage-core

What should I do

Thank you ,
Note

**Comment by cyenyxe** [comment]
Pre-compiled versions of Biodata and OpenCGA are now downloaded automatically. If you have a Mongo instance (and optionally VEP) set up, you can skip straight to the _Build_ section. We will update the README file to avoid any confusion.

**Comment by silenus092** [comment]
Hmm so If I clone and build it now the pre-compiled versions of Biodata and OpenCGA  are included , then how about opencga path inside a application.properties file , just leave it blank?

**Comment by cyenyxe** [comment]
It is true that you still need to have access to the OpenCGA configuration folder. We will update the repository structure to make this as straightforward as possible for you.

**Comment by cyenyxe** [comment]
@silenus092 we have merged a PR that makes all the OpenCGA configuration files available in our repository. Please let us know if this helps and if have any other issues trying to run the pipeline.
