### ISSUE TITLE
Chunk size parameter should be optional

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/eva-pipeline#133]
The application fails if the `config.chunk.size` parameter is not provided. A better approach would be to use a default value like 500, which allows the pipeline to progress without too much contention but at the same time ensures the memory usage is not too high.

**Comment by AdrianBZG** [comment]
Hi, is this not already implemented? I can see in ChuckSizeParameters (line 29), the default value is 1000, and that's it's an optional parameter, as it's handled in LoadVariantsStepParametersValidator (line 73)... right? Or I'm wrong?

**Comment by jmmut** [comment]
Yes, it seems it's already implemented (LoadVariantsStepParametersValidatorTest::allJobParametersAreValid). A tricky explanation might be that we are allowing to omit the parameter, but this: `config.chunk.size=` defines chunkSize as null, which we forbid.

I say we close this issue as already done

**Comment by cyenyxe** [comment]
I will do a test run before we close it, just in case.

**Comment by 108krohan** [comment]
Hi! I have tested the issue and seems like it is safe to mark it as resolved. Here are my observations: 

#### Case 1: chunk size parameter set (`config.chunk.size=5000`)

**observation** job runs with step size = 5000

`sudo java -jar /Users/rohnkum/ga4gh/eva-pipeline/target/eva-pipeline-2.1-SNAPSHOT-7d19c72.jar \
--spring.config.location=file:/Users/rohnkum/ga4gh/eva-pipeline/examples/application.properties --parameters.path=/Users/rohnkum/ga4gh/eva-pipeline/examples/load-genotyped-vcf.properties | tee logs-chunksize-5000.txt`

#### Case 2: chunk size parameter only key provided (`config.chunk.size=`) - 

**observation** uses default value = 1000

`sudo java -jar /Users/rohnkum/ga4gh/eva-pipeline/target/eva-pipeline-2.1-SNAPSHOT-7d19c72.jar \
--spring.config.location=file:/Users/rohnkum/ga4gh/eva-pipeline/examples/application.properties --parameters.path=/Users/rohnkum/ga4gh/eva-pipeline/examples/load-genotyped-vcf.properties | tee logs-chunksize-provided-but-not-set-uses-default-1000.txt`

#### Case 3: chunk size parameter not provided (param missing)

**observation** uses default value = 1000

`sudo java -jar /Users/rohnkum/ga4gh/eva-pipeline/target/eva-pipeline-2.1-SNAPSHOT-7d19c72.jar \
--spring.config.location=file:/Users/rohnkum/ga4gh/eva-pipeline/examples/application.properties --parameters.path=/Users/rohnkum/ga4gh/eva-pipeline/examples/load-genotyped-vcf.properties | tee logs-chunksize-not-provided-uses-default-1000.txt`

I had shared the log files with @sundarvenkata-EBI 
However, if it is known for sure the issue exists then please let me know if there's a way to reproduce the error on my machine and I'd be happy to apply a patch.
