### ISSUE TITLE
Integrate ETL pipeline with auto-mapped variation-commons models

### ISSUE THREAD

**Issue by sundarvenkata-EBI** [EBIvariation/eva-pipeline#147]
[**variation-commons**](https://github.com/EBIvariation/variation-commons) and **eva-pipeline** have different definitions of models and converters between Java classes and MongoDB documents. variation-commons has been recently reworked to facilitate reading from MongoDB.

Make eva-pipeline use the new classes from variation-commons.

**Comment by tcezard** [comment]
Already tracked in EVA-685: closing
